[package]
name = "cargo-binstall"
description = "Rust binary package installer for CI integration"
repository = "https://github.com/ryankurte/cargo-binstall"
documentation = "https://docs.rs/cargo-binstall"
version = "0.7.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2018"
license = "GPL-3.0"


[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ format }"
bin-dir = "{ bin }{ format }"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"
[package.metadata.binstall.overrides.x86_64-apple-darwin]
pkg-fmt = "zip"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.52"
cargo_metadata = "0.14.2"
cargo_toml = "0.11.4"
crates_io_api = { version = "0.8.0", default-features = false, features = ["rustls"] }
dirs = "4.0.0"
flate2 = "1.0.22"
log = "0.4.14"
reqwest = { version = "0.11.10", features = [ "rustls-tls" ], default-features = false }
semver = "1.0.7"
serde = { version = "1.0.136", features = [ "derive" ] }
simplelog = "0.12.0"
structopt = "0.3.26"
strum = "0.24.0"
strum_macros = "0.24.0"
tar = "0.4.38"
tempfile = "3.3.0"
tinytemplate = "1.2.1"

# This crate uses features rt-multi-thread and macros in `#[tokio::main]` and
# uses feature process to create process.
tokio = { version = "1.18.0", features = [ "rt-multi-thread", "macros", "process" ], default-features = false }
url = "2.2.2"
xz2 = "0.1.6"
# Disable all features of zip except for features of compression algorithms:
# Disable features include:
#  - aes-crypto: Enables decryption of files which were encrypted with AES, absolutely zero use for
#    this crate.
#  - time: Enables features using the [time](https://github.com/time-rs/time) crate,
#    which is not used by this crate.
zip = { version = "0.6.2", default-features = false, features = [ "deflate", "bzip2", "zstd" ] }
# zstd is also depended by zip.
# Since zip 0.6.2 depends on zstd 0.10.0, we also have to use 0.10.0 here,
# otherwise there will be a link conflict.
#
# Enable feature bindgen to generate C bindings.
# Enable feature zstdmt to enable multithreading in libzstd.
zstd = { version = "0.10.0", features = [ "bindgen", "zstdmt" ], default-features = false }

[dev-dependencies]
env_logger = "0.9.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
